import type { Permission, Role } from "@/types";
import { daysAgo } from "./seed";

export const roles: Role[] = [
  {
    id: "role-01",
    code: "super-admin",
    name: "超级管理员",
    description: "平台最高权限，可管理全部租户、模型、密钥与系统设置，操作全程审计。",
    scope: "platform",
    level: 100,
    isSystem: true,
    userCount: 4,
    permissions: ["perm-01", "perm-02", "perm-03", "perm-06", "perm-07", "perm-11", "perm-16", "perm-21", "perm-23"],
    updatedAt: daysAgo(12, 10, 24),
  },
  {
    id: "role-02",
    code: "tenant-admin",
    name: "租户管理员",
    description: "管理所属租户的组织、成员、项目、配额与租户级策略，不能跨租户操作。",
    scope: "tenant",
    level: 80,
    isSystem: true,
    userCount: 37,
    permissions: ["perm-01", "perm-04", "perm-06", "perm-08", "perm-12", "perm-17", "perm-22", "perm-24"],
    updatedAt: daysAgo(20, 15, 8),
  },
  {
    id: "role-03",
    code: "model-reviewer",
    name: "模型审核员",
    description: "审核自定义模型接入、BYOK 密钥、模型路由与数据流向，可执行模型验证。",
    scope: "platform",
    level: 70,
    isSystem: true,
    userCount: 9,
    permissions: ["perm-06", "perm-07", "perm-09", "perm-10", "perm-11", "perm-20"],
    updatedAt: daysAgo(6, 11, 45),
  },
  {
    id: "role-04",
    code: "key-custodian",
    name: "密钥管理员",
    description: "负责密钥保险箱轮换、撤销与离职回收，不接触模型业务配置。",
    scope: "platform",
    level: 65,
    isSystem: true,
    userCount: 5,
    permissions: ["perm-07", "perm-11", "perm-13", "perm-20"],
    updatedAt: daysAgo(9, 9, 30),
  },
  {
    id: "role-05",
    code: "security-auditor",
    name: "安全审计",
    description: "只读访问审计日志、告警、DLP 命中记录，可导出合规证据，不可修改配置。",
    scope: "platform",
    level: 60,
    isSystem: true,
    userCount: 7,
    permissions: ["perm-01", "perm-05", "perm-14", "perm-18", "perm-19", "perm-25"],
    updatedAt: daysAgo(15, 14, 12),
  },
  {
    id: "role-06",
    code: "finance",
    name: "财务",
    description: "管理套餐、账单、发票、成本中心与预算告警，可查看用量不可管理成员。",
    scope: "tenant",
    level: 55,
    isSystem: true,
    userCount: 11,
    permissions: ["perm-01", "perm-15", "perm-17", "perm-24", "perm-26"],
    updatedAt: daysAgo(3, 16, 40),
  },
  {
    id: "role-07",
    code: "readonly",
    name: "只读观察员",
    description: "仅可查看被授权的项目与报表，任何写操作都会被拒绝并记录审计。",
    scope: "project",
    level: 10,
    isSystem: true,
    userCount: 128,
    permissions: ["perm-01", "perm-05", "perm-19"],
    updatedAt: daysAgo(40, 10, 5),
  },
  {
    id: "role-08",
    code: "platform-operator",
    name: "平台运营",
    description: "负责 Agent 市场、公告、活动与工单，可管理上架与推荐位。",
    scope: "platform",
    level: 50,
    isSystem: false,
    userCount: 6,
    permissions: ["perm-01", "perm-04", "perm-12", "perm-22", "perm-26"],
    updatedAt: daysAgo(2, 18, 22),
  },
  {
    id: "role-09",
    code: "developer",
    name: "开发者",
    description: "在项目内使用 Agent、执行工具与沙箱，受项目策略与审批链约束。",
    scope: "project",
    level: 30,
    isSystem: true,
    userCount: 486,
    permissions: ["perm-01", "perm-12", "perm-17", "perm-22"],
    updatedAt: daysAgo(28, 13, 55),
  },
];

const PERMISSION_SEEDS: [string, string, string, string, Permission["action"], boolean][] = [
  ["tenant", "租户", "租户信息", "查看与编辑租户资料、套餐与状态", "write", false],
  ["tenant", "租户", "租户开通", "创建、开通与注销租户", "admin", true],
  ["tenant", "租户", "租户删除", "删除租户及其全部数据", "delete", true],
  ["tenant", "组织", "组织架构", "维护组织、部门、团队层级", "write", false],
  ["tenant", "组织", "项目归属", "调整项目所属组织与负责人", "write", false],
  ["user", "成员", "成员查看", "查看成员列表与详情", "read", false],
  ["user", "成员", "成员管理", "邀请、禁用、删除成员", "write", true],
  ["user", "成员", "批量导入", "通过 CSV/SCIM 批量导入成员", "write", true],
  ["user", "身份", "SSO 配置", "配置 OIDC/SAML/LDAP/企业微信等身份源", "admin", true],
  ["user", "身份", "SCIM 同步", "启用与调整 SCIM 目录同步", "admin", true],
  ["model", "平台模型", "模型上架", "上架、下架与调整平台模型可见范围", "approve", true],
  ["model", "自定义模型", "模型接入审批", "审批 BYOK、自定义 Endpoint、本地模型接入", "approve", true],
  ["model", "模型密钥", "密钥托管", "创建、轮换、撤销 BYOK 密钥", "admin", true],
  ["model", "模型验证", "执行验证", "运行连通性、流式、工具调用等验证项", "execute", false],
  ["model", "模型路由", "路由策略", "配置路由、Fallback 与降级费用归属", "write", true],
  ["tool", "工具", "工具注册", "注册自定义工具与 OpenAPI 导入", "write", true],
  ["tool", "工具", "命令策略", "维护允许/禁止命令与 sudo 策略", "admin", true],
  ["tool", "MCP", "MCP 管理", "管理 MCP Server、鉴权与网络策略", "admin", true],
  ["project", "项目", "项目策略", "配置项目预算、模型策略、敏感文件保护", "write", false],
  ["project", "沙箱", "沙箱管理", "管理镜像、配额、网络与回收策略", "admin", true],
  ["billing", "账单", "账单与发票", "查看账单、开具发票与处理退款", "write", true],
  ["billing", "预算", "预算与告警", "维护预算、成本中心与超支告警", "write", false],
  ["audit", "审计", "审计日志", "查看与导出审计日志", "read", false],
  ["audit", "审计", "合规证据", "导出合规证据包与保留策略", "read", true],
  ["security", "安全", "DLP 与内容审核", "维护 DLP、内容过滤与注入防护规则", "admin", true],
  ["monitoring", "监控", "告警规则", "维护告警规则与通知渠道", "write", false],
  ["integration", "集成", "第三方集成", "安装与授权 Git/IM/CI 集成", "admin", true],
  ["experiment", "实验", "开关与灰度", "管理功能开关、灰度与 A/B 实验", "write", true],
  ["setting", "设置", "系统设置", "修改平台全局设置与私有化配置", "admin", true],
];

export const permissions: Permission[] = PERMISSION_SEEDS.map(
  ([module, resource, name, description, action, sensitive], index) => ({
    id: `perm-${String(index + 1).padStart(2, "0")}`,
    code: `${module}.${action}.${String(index + 1).padStart(2, "0")}`,
    name,
    module,
    resource,
    action,
    description,
    roles: roles.filter((role) => role.permissions.includes(`perm-${String(index + 1).padStart(2, "0")}`)).map((role) => role.id),
    sensitive,
  }),
);

export const permissionModules = Array.from(new Set(permissions.map((permission) => permission.module)));
