<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.hucoo</groupId>
        <artifactId>hucoo-module</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>hucoo-module-file</artifactId>
    <name>hucoo-module-file</name>
    <description>文件元数据、上传下载、分享链接与存储治理</description>

    <dependencies>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.hucoo</groupId>
            <artifactId>hucoo-commons-api</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.hucoo</groupId>
            <artifactId>hucoo-commons-dto</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.hucoo</groupId>
            <artifactId>hucoo-commons-exception</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.hucoo</groupId>
            <artifactId>hucoo-commons-util</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.hucoo</groupId>
            <artifactId>hucoo-component-web</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.hucoo</groupId>
            <artifactId>hucoo-component-security</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.hucoo</groupId>
            <artifactId>hucoo-component-database</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.hucoo</groupId>
            <artifactId>hucoo-component-observability</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.hucoo</groupId>
            <artifactId>hucoo-component-storage</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>dev.hucoo</groupId>
            <artifactId>hucoo-component-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
