package dev.hucoo.modelruntime.domain;

public enum FailureClass {
    AUTHENTICATION, INSUFFICIENT_BALANCE, RATE_LIMITED, TIMEOUT, CONNECTION,
    PROVIDER_5XX, INVALID_REQUEST, CONTENT_FILTERED, CAPABILITY_UNSUPPORTED, UNKNOWN
}
