-- Governance, runtime, billing, security and operations schema.

CREATE TABLE IF NOT EXISTS ap_model_provider (id BIGINT NOT NULL PRIMARY KEY, provider_code VARCHAR(64) NOT NULL, provider_name VARCHAR(128) NOT NULL, endpoint VARCHAR(512), status INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_ap_model_provider_code UNIQUE (tenant_id, provider_code));
CREATE TABLE IF NOT EXISTS ap_custom_model_registration (id BIGINT NOT NULL PRIMARY KEY, model_code VARCHAR(128) NOT NULL, provider_id BIGINT, visibility VARCHAR(32), approval_status VARCHAR(32) DEFAULT 'PENDING', endpoint VARCHAR(512), key_ref VARCHAR(256), key_fingerprint VARCHAR(128), status INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_ap_custom_model_code UNIQUE (tenant_id, model_code));
CREATE TABLE IF NOT EXISTS ap_model_validation_run (id BIGINT NOT NULL PRIMARY KEY, model_id BIGINT NOT NULL, status VARCHAR(32) DEFAULT 'PENDING', progress INT DEFAULT 0, retry_count INT DEFAULT 0, failure_reason VARCHAR(1024), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_routing_rule (id BIGINT NOT NULL PRIMARY KEY, rule_name VARCHAR(128) NOT NULL, primary_model VARCHAR(128), fallback_model VARCHAR(128), priority INT DEFAULT 0, fallback_condition VARCHAR(512), cost_owner VARCHAR(64), status INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_tool_definition (id BIGINT NOT NULL PRIMARY KEY, tool_code VARCHAR(128) NOT NULL, tool_name VARCHAR(128) NOT NULL, parameter_schema TEXT, risk_level VARCHAR(32), requires_approval INT DEFAULT 0, status INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_ap_tool_code UNIQUE (tenant_id, tool_code));
CREATE TABLE IF NOT EXISTS ap_command_policy (id BIGINT NOT NULL PRIMARY KEY, policy_name VARCHAR(128) NOT NULL, pattern VARCHAR(512) NOT NULL, effect VARCHAR(32), scope VARCHAR(64), enabled INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_network_policy (id BIGINT NOT NULL PRIMARY KEY, policy_name VARCHAR(128) NOT NULL, allowed_domains TEXT, blocked_cidrs TEXT, transport VARCHAR(64), enabled INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_mcp_server_review (id BIGINT NOT NULL PRIMARY KEY, server_id BIGINT NOT NULL, status VARCHAR(32) DEFAULT 'PENDING', reviewer_id BIGINT, reason VARCHAR(1024), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_agent_version (id BIGINT NOT NULL PRIMARY KEY, agent_id BIGINT NOT NULL, version_code VARCHAR(64) NOT NULL, prompt TEXT, model_policy TEXT, tool_allowlist TEXT, knowledge_refs TEXT, release_status VARCHAR(32) DEFAULT 'DRAFT', tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_market_listing (id BIGINT NOT NULL PRIMARY KEY, resource_type VARCHAR(64) NOT NULL, resource_id BIGINT NOT NULL, listing_status VARCHAR(32) DEFAULT 'DRAFT', recommended INT DEFAULT 0, score NUMERIC(10,2), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_project_policy (id BIGINT NOT NULL PRIMARY KEY, project_id BIGINT NOT NULL, model_policy TEXT, tool_policy TEXT, budget NUMERIC(18,6), sensitive_file_policy TEXT, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_workspace_resource (id BIGINT NOT NULL PRIMARY KEY, workspace_id BIGINT NOT NULL, cpu VARCHAR(32), memory VARCHAR(32), disk VARCHAR(32), gpu VARCHAR(64), concurrency_limit INT, idle_timeout_seconds INT, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_sandbox (id BIGINT NOT NULL PRIMARY KEY, sandbox_code VARCHAR(128) NOT NULL, image VARCHAR(512) NOT NULL, network_policy VARCHAR(64), compliance_baseline VARCHAR(128), vulnerability_count INT DEFAULT 0, status VARCHAR(32), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_ap_sandbox_code UNIQUE (tenant_id, sandbox_code));
CREATE TABLE IF NOT EXISTS ap_image_scan (id BIGINT NOT NULL PRIMARY KEY, sandbox_id BIGINT NOT NULL, status VARCHAR(32), risk_level VARCHAR(32), vulnerability_count INT DEFAULT 0, compliance_status VARCHAR(32), scanned_at TIMESTAMP(6), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_usage_summary (id BIGINT NOT NULL PRIMARY KEY, period VARCHAR(32) NOT NULL, project_id BIGINT, model_code VARCHAR(128), calls BIGINT DEFAULT 0, input_tokens BIGINT DEFAULT 0, output_tokens BIGINT DEFAULT 0, amount NUMERIC(18,6) DEFAULT 0, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_billing_plan (id BIGINT NOT NULL PRIMARY KEY, plan_code VARCHAR(64) NOT NULL, plan_name VARCHAR(128) NOT NULL, monthly_price NUMERIC(18,6), model_fee NUMERIC(18,6), byok_fee NUMERIC(18,6), status INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_ap_billing_plan_code UNIQUE (tenant_id, plan_code));
CREATE TABLE IF NOT EXISTS ap_invoice (id BIGINT NOT NULL PRIMARY KEY, invoice_no VARCHAR(64) NOT NULL, period VARCHAR(32) NOT NULL, plan_id BIGINT, seats INT, model_fees NUMERIC(18,6), byok_fee NUMERIC(18,6), total_amount NUMERIC(18,6), status VARCHAR(32) DEFAULT 'ISSUED', tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_ap_invoice_no UNIQUE (tenant_id, invoice_no));
CREATE TABLE IF NOT EXISTS ap_cost_center (id BIGINT NOT NULL PRIMARY KEY, center_code VARCHAR(64) NOT NULL, center_name VARCHAR(128) NOT NULL, owner_id BIGINT, budget NUMERIC(18,6), spent NUMERIC(18,6) DEFAULT 0, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_budget_alert (id BIGINT NOT NULL PRIMARY KEY, center_id BIGINT, threshold_percent NUMERIC(5,2), enabled INT DEFAULT 1, last_triggered_at TIMESTAMP(6), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_dlp_rule (id BIGINT NOT NULL PRIMARY KEY, rule_name VARCHAR(128) NOT NULL, pattern TEXT NOT NULL, category VARCHAR(64), action VARCHAR(32), scope VARCHAR(64), enabled INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_content_filter_rule (id BIGINT NOT NULL PRIMARY KEY, rule_name VARCHAR(128) NOT NULL, stage VARCHAR(32), category VARCHAR(64), action VARCHAR(32), severity VARCHAR(32), enabled INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_ip_allowlist (id BIGINT NOT NULL PRIMARY KEY, cidr VARCHAR(128) NOT NULL, label VARCHAR(128), scope VARCHAR(64), effect VARCHAR(32), expires_at TIMESTAMP(6), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_data_retention_policy (id BIGINT NOT NULL PRIMARY KEY, data_type VARCHAR(64) NOT NULL, retention_days INT NOT NULL, deletion_mode VARCHAR(32), export_enabled INT DEFAULT 0, jurisdiction VARCHAR(64), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_compliance_item (id BIGINT NOT NULL PRIMARY KEY, item_code VARCHAR(64) NOT NULL, item_name VARCHAR(128) NOT NULL, status VARCHAR(32), owner_id BIGINT, due_at TIMESTAMP(6), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_notification_channel (id BIGINT NOT NULL PRIMARY KEY, channel_type VARCHAR(32) NOT NULL, channel_name VARCHAR(128) NOT NULL, config_ref VARCHAR(256), enabled INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_alert (id BIGINT NOT NULL PRIMARY KEY, rule_id BIGINT, severity VARCHAR(32), status VARCHAR(32), message VARCHAR(1024), fired_at TIMESTAMP(6), resolved_at TIMESTAMP(6), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_webhook_endpoint (id BIGINT NOT NULL PRIMARY KEY, name VARCHAR(128) NOT NULL, url VARCHAR(512) NOT NULL, events TEXT, secret_ref VARCHAR(256), enabled INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_announcement (id BIGINT NOT NULL PRIMARY KEY, title VARCHAR(256) NOT NULL, content TEXT, status VARCHAR(32), published_at TIMESTAMP(6), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ap_experiment (id BIGINT NOT NULL PRIMARY KEY, experiment_key VARCHAR(128) NOT NULL, experiment_name VARCHAR(128) NOT NULL, experiment_type VARCHAR(32), traffic_percent NUMERIC(5,2), audience TEXT, metric VARCHAR(128), status VARCHAR(32), tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_ap_experiment_key UNIQUE (tenant_id, experiment_key));
CREATE TABLE IF NOT EXISTS ap_platform_setting (id BIGINT NOT NULL PRIMARY KEY, setting_group VARCHAR(64) NOT NULL, setting_key VARCHAR(128) NOT NULL, setting_value TEXT, default_value TEXT, version_no INT DEFAULT 1, tenant_id VARCHAR(64) DEFAULT '000000', version INT DEFAULT 0, deleted INT DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uk_ap_setting_key UNIQUE (tenant_id, setting_group, setting_key));

DO $$ DECLARE t TEXT; c TEXT; BEGIN
  FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name IN ('ap_model_provider', 'ap_custom_model_registration', 'ap_model_validation_run', 'ap_routing_rule', 'ap_tool_definition', 'ap_command_policy', 'ap_network_policy', 'ap_mcp_server_review', 'ap_agent_version', 'ap_market_listing', 'ap_project_policy', 'ap_workspace_resource', 'ap_sandbox', 'ap_image_scan', 'ap_usage_summary', 'ap_billing_plan', 'ap_invoice', 'ap_cost_center', 'ap_budget_alert', 'ap_dlp_rule', 'ap_content_filter_rule', 'ap_ip_allowlist', 'ap_data_retention_policy', 'ap_compliance_item', 'ap_notification_channel', 'ap_alert', 'ap_webhook_endpoint', 'ap_announcement', 'ap_experiment', 'ap_platform_setting') LOOP
    EXECUTE format('COMMENT ON TABLE %I IS %L', t, replace(t, 'ap_', '管理端业务表：'));
    FOR c IN SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = t LOOP
      EXECUTE format('COMMENT ON COLUMN %I.%I IS %L', t, c, '字段：' || c);
    END LOOP;
  END LOOP;
END $$;
